"use client";
import { useMemo, useState } from "react";
import { InvoiceStatusSelect } from "@/components/invoices/invoice-status-select";
import { SendDocumentEmailButton } from "@/components/invoices/send-document-email-button";
export function InvoiceList({ invoices }: { invoices: any[] }) {
  const [q, setQ] = useState(""); const [page, setPage] = useState(1); const size = 10;
  const filtered = useMemo(() => invoices.filter(i => `${i.number} ${i.customer.name}`.toLowerCase().includes(q.toLowerCase())), [invoices, q]);
  const pages = Math.max(1, Math.ceil(filtered.length / size)); const rows = filtered.slice((page - 1) * size, page * size);
  return <><input value={q} onChange={e => { setQ(e.target.value); setPage(1); }} placeholder="Rechercher par numéro ou client…" className="mb-4 w-full rounded-lg border bg-white p-3" /><div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[820px] text-sm"><thead className="bg-slate-50 dark:bg-slate-800/70"><tr><th className="p-4 text-left">Numéro</th><th className="p-4 text-left">Client</th><th className="p-4 text-left">Date</th><th className="p-4 text-left">Statut</th><th className="p-4 text-right">Total</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{rows.map(i => <tr key={i.id} className="border-t"><td className="p-4 font-medium">{i.number}</td><td className="p-4">{i.customer.name}</td><td className="p-4">{new Date(i.issueDate).toLocaleDateString("fr-FR")}</td><td className="p-4"><InvoiceStatusSelect id={i.id} status={i.status}/></td><td className="p-4 text-right font-semibold">{Number(i.total).toLocaleString("fr-FR",{style:"currency",currency:i.currency})}</td><td className="p-4"><div className="flex flex-wrap items-center justify-end gap-3"><a href={`/api/invoices/${i.id}/pdf`} target="_blank" rel="noreferrer" className="text-blue-600 hover:underline">PDF</a><SendDocumentEmailButton id={i.id} recipient={i.customer.email}/></div></td></tr>)}</tbody></table>{!rows.length&&<p className="p-10 text-center text-slate-500">Aucun résultat.</p>}</div><div className="mt-4 flex items-center justify-between text-sm text-slate-500"><span>{filtered.length} résultat(s)</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(page-1)} className="rounded border px-3 py-1 disabled:opacity-40">Précédent</button><span className="px-2 py-1">Page {page}/{pages}</span><button disabled={page>=pages} onClick={()=>setPage(page+1)} className="rounded border px-3 py-1 disabled:opacity-40">Suivant</button></div></div></>;
}
