import { listProducts } from "@/services/product.service";
import { createProductAction } from "@/actions/product.actions"; import {ProductList} from "@/components/products/product-list";
export default async function ProductsPage(){
 const products=await listProducts();
 return <main className="min-h-screen p-6 md:p-10"><div className="mx-auto max-w-7xl">
 <header><p className="text-sm font-medium text-blue-600">Catalogue</p><h1 className="text-3xl font-bold">Produits</h1><p className="mt-1 text-slate-500">Produits, variantes et niveaux de stock.</p></header>
 <form action={createProductAction} className="mt-6 grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-6">
 {["sku","name","price","costPrice","stock","minStock"].map((n)=><input key={n} name={n} required={["sku","name"].includes(n)} type={["price","costPrice","stock","minStock"].includes(n)?"number":"text"} step={["price","costPrice"].includes(n)?".01":undefined} placeholder={n==="costPrice"?"Coût":n==="minStock"?"Seuil":n==="sku"?"SKU":n==="name"?"Nom":n} className="rounded-lg border p-2"/>)} 
 <button className="rounded-lg bg-slate-900 px-4 py-2 font-semibold text-white md:col-span-6">Ajouter le produit</button></form>
 <div className="mt-6"><ProductList products={products}/></div></main></div>stProducts } from "@/services/product.service";
import { createProductAction,deleteProductAction,createVariantAction } from "@/actions/product.actions";
export default async function ProductsPage(){
 const products=await listProducts();
 return <main className="min-h-screen p-6 md:p-10"><div className="mx-auto max-w-7xl">
 <header><p className="text-sm font-medium text-blue-600">Catalogue</p><h1 className="text-3xl font-bold">Produits</h1><p className="mt-1 text-slate-500">Produits, variantes et niveaux de stock.</p></header>
 <form action={createProductAction} className="mt-6 grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-6">
 {["sku","name","price","costPrice","stock","minStock"].map((n)=><input key={n} name={n} required={["sku","name"].includes(n)} type={["price","costPrice","stock","minStock"].includes(n)?"number":"text"} step={["price","costPrice"].includes(n)?".01":undefined} placeholder={n==="costPrice"?"Coût":n==="minStock"?"Seuil":n==="sku"?"SKU":n==="name"?"Nom":n} className="rounded-lg border p-2"/>)} 
 <button className="rounded-lg bg-slate-900 px-4 py-2 font-semibold text-white md:col-span-6">Ajouter le produit</button></form>
 <div className="mt-6 space-y-4">{products.map(p=><article key={p.id} className="overflow-hidden rounded-2xl border bg-white shadow-sm">
 <div className="flex flex-col gap-3 p-5 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-medium text-slate-500">{p.sku}</p><h2 className="text-lg font-semibold">{p.name}</h2></div><div className="flex items-center gap-3"><span className="text-sm">{p.stock} en stock</span>{p.stock<=p.minStock?<span className="rounded-full bg-red-100 px-2 py-1 text-xs text-red-700">Alerte</span>:<span className="rounded-full bg-green-100 px-2 py-1 text-xs text-green-700">OK</span>}<form action={deleteProductAction.bind(null,p.id)}><button className="text-sm text-red-600">Supprimer</button></form></div></div>
 <div className="border-t bg-slate-50/70 p-5"><div className="mb-3 flex items-center justify-between"><h3 className="font-medium">Variantes ({p.variants.length})</h3></div>
 {p.variants.length>0&&<div className="mb-4 space-y-2">{p.variants.map(v=><div key={v.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border bg-white p-3 text-sm"><span className="font-medium">{v.name}</span><span>{v.sku}</span><span>{v.size||"—"} / {v.color||"—"}</span><span>{v.stock} stock</span></div>)}</div>}
 <form action={createVariantAction.bind(null,p.id)} className="grid gap-2 md:grid-cols-6"><input name="sku" required placeholder="SKU variante" className="rounded-lg border p-2"/><input name="name" required placeholder="Nom" className="rounded-lg border p-2"/><input name="size" placeholder="Taille" className="rounded-lg border p-2"/><input name="color" placeholder="Couleur" className="rounded-lg border p-2"/><input name="stock" type="number" placeholder="Stock" className="rounded-lg border p-2"/><input name="minStock" type="number" placeholder="Seuil" className="rounded-lg border p-2"/><button className="rounded-lg bg-slate-800 px-3 py-2 text-sm font-medium text-white md:col-span-6">Ajouter une variante</button></form></div></article>)}</div>
 {products.length===0&&<p className="mt-6 rounded-2xl border p-10 text-center text-slate-500">Aucun produit.</p>}</div></main>}